
name: My-1st-CI/CD
env:
  APPLICATION_NAME: "My Flask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"


on:
   push:
     branches:
       - main

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
     - name: Print "Hello Message testing"
       run: echo "Hello World from Testing"
       
     - name: Execute few  commands
       run: |
        echo "Hello Message 1"
        echo "Hello Message 2"
        echo "Aplication name ${{env.APPLICATION_NAME}}"

     - name:  GitClone MyRepo
       uses: actions/chekout@v3
       
     - name: List Current Folder
       run: ls -la



  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    steps:
     - name: Print "Hello Message deploy"
       run: echo "Hello World from Deploy"
       
     - name : Printing Deployment Package
       run: echo "Deploy package name is ${{env.DEPLOY_PACKAGE_NAME}}"

     - name: Lets test some Packages if they are here 1
       run: aws --version

     - name: Lets test some Packages if they are here 2
       run: aws --zip
